"""initial schema

Revision ID: 02c9bddb8d73
Revises: 
Create Date: 2026-04-07 22:19:33.890838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c9bddb8d73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_symbol'), 'alert_logs', ['symbol'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('signal', sa.Enum('STRONG_BUY', 'BUY', 'HOLD', 'SELL', 'STRONG_SELL', name='signal_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_symbol'), 'analysis_results', ['symbol'], unique=False)
    op.create_index(op.f('ix_analysis_results_timestamp'), 'analysis_results', ['timestamp'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('avg_buy_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.create_table('ohlcv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ohlcv_data_symbol'), 'ohlcv_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_ohlcv_data_timestamp'), 'ohlcv_data', ['timestamp'], unique=False)
    op.create_table('prediction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('predicted_signal', sa.String(length=20), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('actual_outcome', sa.String(length=10), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_history_symbol'), 'prediction_history', ['symbol'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('alert_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_prediction_history_symbol'), table_name='prediction_history')
    op.drop_table('prediction_history')
    op.drop_index(op.f('ix_ohlcv_data_timestamp'), table_name='ohlcv_data')
    op.drop_index(op.f('ix_ohlcv_data_symbol'), table_name='ohlcv_data')
    op.drop_table('ohlcv_data')
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_analysis_results_timestamp'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_symbol'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_alert_logs_symbol'), table_name='alert_logs')
    op.drop_table('alert_logs')
    # ### end Alembic commands ###
